<!DOCTYPE html>
<html dir="{{ $rtl ? 'rtl' : 'ltr' }}" lang="{{ app()->getLocale() }}">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ __('Payment Receipt') }}</title>
    <style>
        @font-face {
            font-family: 'Noto Sans Arabic';
            font-style: normal;
            font-weight: 400;
            src: url({{ storage_path('fonts/NotoSansArabic-Regular.ttf') }}) format('truetype');
        }

        body {
            font-family: 'Noto Sans Arabic', 'DejaVu Sans', sans-serif;
            line-height: 1.6;
            direction: {{ $rtl ? 'rtl' : 'ltr' }};
        }
        
        .arabic-text {
            font-family: 'Noto Sans Arabic';
            font-size: 14px;
        }

        .header {
            text-align: center;
            margin-bottom: 25px;
        }
        
        .details-table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        
        .details-table td {
            padding: 8px;
            border-bottom: 1px solid #ddd;
            text-align: {{ $rtl ? 'right' : 'left' }};
        }
    </style>
</head>
<body>
    <div class="header">
        <h1 class="arabic-text">{{ __('Payment Receipt') }}</h1>
        <p class="arabic-text">{{ __('Official Transaction Record') }}</p>
    </div>

    <table class="details-table">
        <tr>
            <td class="arabic-text"><strong>{{ __('Reference Number') }}:</strong></td>
            <td class="arabic-text">{{ $payment->reference }}</td>
        </tr>
        <tr>
            <td class="arabic-text"><strong>{{ __('Date & Time') }}:</strong></td>
            <td class="arabic-text">{{ $payment->created_at->format('d/m/Y H:i') }}</td>
        </tr>
        <tr>
            <td class="arabic-text"><strong>{{ __('Amount Paid') }}:</strong></td>
            <td class="arabic-text">{{ number_format($payment->amount, 2) }} {{ $payment->currency }}</td>
        </tr>
        <tr>
            <td class="arabic-text"><strong>{{ __('Status') }}:</strong></td>
            <td class="arabic-text">{{ __(ucfirst($payment->status)) }}</td>
        </tr>
    </table>

    <div class="footer arabic-text" style="margin-top: 30px;">
        <p>{{ __('This is an official receipt generated by') }} {{ config('app.name') }}</p>
        <small>{{ __('Transaction ID') }}: {{ $payment->id }}</small>
    </div>
</body>
</html>